[package]
name = "net-reduce"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
prefix-trie = { version = "0.8.0", features = ["ipnet", "cidr"] }
clap = { version = "4.5.40", features = ["derive"] }
ipnet = "2.11.0"
